import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('설문/인터뷰 샘플 데이터 생성 시작...')

  // 기존 데이터 삭제 (선택사항)
  // await prisma.labSurvey.deleteMany()

  const surveys = [
    // 진행중 설문조사
    {
      title: '북한이탈주민 정착 실태조사 2026',
      description: '북한이탈주민의 한국 사회 정착 과정에서 경험하는 어려움과 지원 서비스 이용 현황을 파악하기 위한 설문조사입니다. 본 조사 결과는 정착 지원 정책 개선을 위한 기초자료로 활용됩니다.',
      type: 'SURVEY',
      targetCount: 200,
      currentCount: 87,
      targetCategories: JSON.stringify(['DEFECTOR']),
      targetAgeMin: 19,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: '입국 후 1년 이상 경과자',
      questionCount: 45,
      estimatedTime: 20,
      externalUrl: 'https://forms.google.com/survey-example-1',
      rewardType: 'CASH',
      rewardAmount: 15000,
      rewardNote: '설문 완료 후 7일 이내 계좌 입금',
      startDate: new Date('2026-01-01'),
      endDate: new Date('2026-02-28'),
      isExternal: true,
      requesterOrg: '통일연구원',
      status: 'RECRUITING',
      isPublic: true,
    },
    {
      title: '결혼이민자 직업교육 수요조사',
      description: '결혼이민자의 직업 역량 개발을 위한 교육 프로그램 기획에 필요한 수요조사입니다. 희망하는 직업 분야, 교육 방식, 시간대 등을 파악합니다.',
      type: 'SURVEY',
      targetCount: 150,
      currentCount: 42,
      targetCategories: JSON.stringify(['MARRIAGE_IMMIGRANT']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: null,
      questionCount: 30,
      estimatedTime: 15,
      externalUrl: 'https://forms.google.com/survey-example-2',
      rewardType: 'GIFT',
      rewardAmount: 10000,
      rewardNote: '문화상품권 모바일 발송',
      startDate: new Date('2026-01-10'),
      endDate: new Date('2026-02-15'),
      isExternal: false,
      requesterOrg: '유니피벗',
      status: 'RECRUITING',
      isPublic: true,
    },
    // 진행중 인터뷰
    {
      title: '북한이탈주민 창업 경험 심층인터뷰',
      description: '북한이탈주민 창업자들의 창업 동기, 과정, 성공/실패 요인을 심층적으로 분석하기 위한 인터뷰입니다. 대면 또는 화상 인터뷰로 진행됩니다.',
      type: 'INTERVIEW',
      targetCount: 20,
      currentCount: 8,
      targetCategories: JSON.stringify(['DEFECTOR']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: '창업 경험자 (폐업 포함)',
      questionCount: 15,
      estimatedTime: 60,
      externalUrl: null,
      rewardType: 'CASH',
      rewardAmount: 50000,
      rewardNote: '인터뷰 완료 후 즉시 지급',
      startDate: new Date('2026-01-05'),
      endDate: new Date('2026-03-31'),
      isExternal: true,
      requesterOrg: '서울대학교 통일평화연구원',
      status: 'RECRUITING',
      isPublic: true,
    },
    {
      title: '다문화가정 자녀 진로 상담 연구',
      description: '다문화가정 청소년의 진로 결정 과정과 고민에 대한 심층 인터뷰입니다. 화상 또는 전화 인터뷰로 진행되며, 부모님 동의가 필요합니다.',
      type: 'INTERVIEW',
      targetCount: 30,
      currentCount: 12,
      targetCategories: JSON.stringify(['MULTICULTURAL_CHILD']),
      targetAgeMin: 15,
      targetAgeMax: 24,
      targetGender: 'ANY',
      targetConditions: '중학생 이상, 미혼자',
      questionCount: 20,
      estimatedTime: 45,
      externalUrl: null,
      rewardType: 'GIFT',
      rewardAmount: 30000,
      rewardNote: '문화상품권 지급',
      startDate: new Date('2026-01-15'),
      endDate: new Date('2026-04-30'),
      isExternal: true,
      requesterOrg: '한국청소년정책연구원',
      status: 'RECRUITING',
      isPublic: true,
    },
    // 외국인근로자 대상
    {
      title: '외국인근로자 고용허가제 만족도 조사',
      description: '고용허가제를 통해 한국에서 근무하고 있는 외국인근로자들의 제도 만족도와 개선 요구사항을 조사합니다.',
      type: 'SURVEY',
      targetCount: 300,
      currentCount: 156,
      targetCategories: JSON.stringify(['MIGRANT_WORKER']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: 'E-9 비자 소지자',
      questionCount: 35,
      estimatedTime: 15,
      externalUrl: 'https://forms.google.com/survey-example-3',
      rewardType: 'CASH',
      rewardAmount: 10000,
      rewardNote: '설문 완료 후 3일 이내 송금',
      startDate: new Date('2025-12-15'),
      endDate: new Date('2026-01-31'),
      isExternal: true,
      requesterOrg: '고용노동부',
      status: 'RECRUITING',
      isPublic: true,
    },
    // 유학생 대상
    {
      title: '유학생 한국어 학습 경험 연구',
      description: '외국인 유학생들의 한국어 학습 과정, 어려움, 효과적인 학습 방법에 대한 인터뷰 연구입니다.',
      type: 'INTERVIEW',
      targetCount: 25,
      currentCount: 18,
      targetCategories: JSON.stringify(['INTERNATIONAL_STUDENT']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: '한국 대학 재학생',
      questionCount: 12,
      estimatedTime: 40,
      externalUrl: null,
      rewardType: 'CASH',
      rewardAmount: 30000,
      rewardNote: '인터뷰 후 즉시 송금',
      startDate: new Date('2025-12-01'),
      endDate: new Date('2026-02-28'),
      isExternal: true,
      requesterOrg: '국립국어원',
      status: 'RECRUITING',
      isPublic: true,
    },
    // 완료된 설문
    {
      title: '2025년 이주민 사회통합 실태조사',
      description: '다양한 이주배경을 가진 주민들의 사회통합 수준과 경험을 파악하기 위한 연간 실태조사입니다.',
      type: 'SURVEY',
      targetCount: 500,
      currentCount: 523,
      targetCategories: JSON.stringify(['DEFECTOR', 'MARRIAGE_IMMIGRANT', 'MIGRANT_WORKER', 'NATURALIZED']),
      targetAgeMin: 19,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: null,
      questionCount: 60,
      estimatedTime: 25,
      externalUrl: 'https://forms.google.com/survey-completed-1',
      rewardType: 'CASH',
      rewardAmount: 20000,
      rewardNote: '설문 완료 후 지급 완료',
      startDate: new Date('2025-09-01'),
      endDate: new Date('2025-12-15'),
      isExternal: true,
      requesterOrg: '여성가족부',
      status: 'COMPLETED',
      isPublic: true,
    },
    {
      title: '북한이탈주민 의료 접근성 연구 인터뷰',
      description: '북한이탈주민의 의료 서비스 이용 경험과 접근성 장벽에 대한 심층 인터뷰입니다.',
      type: 'INTERVIEW',
      targetCount: 40,
      currentCount: 40,
      targetCategories: JSON.stringify(['DEFECTOR']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: null,
      questionCount: 18,
      estimatedTime: 50,
      externalUrl: null,
      rewardType: 'CASH',
      rewardAmount: 40000,
      rewardNote: '지급 완료',
      startDate: new Date('2025-08-01'),
      endDate: new Date('2025-11-30'),
      isExternal: true,
      requesterOrg: '고려대학교 의과대학',
      status: 'COMPLETED',
      isPublic: true,
    },
    // 마감된 설문
    {
      title: '난민 정착 지원 서비스 평가',
      description: '난민 인정자 및 인도적 체류자들의 정착 지원 서비스 이용 경험과 만족도를 조사합니다.',
      type: 'SURVEY',
      targetCount: 100,
      currentCount: 100,
      targetCategories: JSON.stringify(['REFUGEE']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: '난민 인정자 또는 인도적 체류자',
      questionCount: 40,
      estimatedTime: 20,
      externalUrl: 'https://forms.google.com/survey-closed-1',
      rewardType: 'GIFT',
      rewardAmount: 15000,
      rewardNote: '상품권 발송 완료',
      startDate: new Date('2025-10-01'),
      endDate: new Date('2025-12-31'),
      isExternal: true,
      requesterOrg: '법무부 출입국외국인정책본부',
      status: 'CLOSED',
      isPublic: true,
    },
    // 임시저장
    {
      title: '재외동포 귀국 정착 경험 조사 (준비중)',
      description: '재외동포의 한국 귀국 후 정착 과정과 경험에 대한 설문조사입니다.',
      type: 'SURVEY',
      targetCount: 150,
      currentCount: 0,
      targetCategories: JSON.stringify(['OVERSEAS_KOREAN']),
      targetAgeMin: null,
      targetAgeMax: null,
      targetGender: 'ANY',
      targetConditions: '귀국 후 5년 이내',
      questionCount: 50,
      estimatedTime: 20,
      externalUrl: null,
      rewardType: 'CASH',
      rewardAmount: 15000,
      rewardNote: null,
      startDate: new Date('2026-03-01'),
      endDate: new Date('2026-05-31'),
      isExternal: false,
      requesterOrg: '재외동포재단',
      status: 'DRAFT',
      isPublic: false,
    },
  ]

  for (const survey of surveys) {
    await prisma.labSurvey.create({
      data: survey,
    })
    console.log(`생성됨: ${survey.title}`)
  }

  console.log(`\n총 ${surveys.length}개의 설문/인터뷰 샘플 데이터가 생성되었습니다.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
